=== dlangille/freshports-1/docs/fp-updates.dtd
<!-- $Id: fp-updates.dtd,v 1.5 2007-10-16 19:02:45 dan Exp $          -->

<!-- http://freshports.org/docs/fp-updates.dtd															-->
<!-- This DTD defines the input to FreshPorts (http://freshports.org/>									-->
<!-- Change History:	0.01	2000.12.27	Initial Release												-->
<!--			0.02	2000.12.27	Added several fields to the COMMIT element;							-->
<!--						Pr, SubmittedBy, ReviewedBy, ApprovedBy and ObtainedFrom					-->
<!--			0.10	2000.12.29	Complete Rewrite.													-->
<!--			0.11	2000.12.30	Renamed OS:System to OS:Id											-->
<!--			0.12	2001.01.04	Removed MESSAGE:Sender attribute									-->
<!--					2002.04.11  Added EncodingLosses 												-->

<!ELEMENT 	UPDATES	(UPDATE+) >
<!ELEMENT 	UPDATE	(DATE, TIME, OS, LOG, PEOPLE, FILES, MESSAGE?, PR?) >

<!-- OS element; Contains the operating system and branch						-->
<!ELEMENT 	OS	EMPTY >
<!ATTLIST	OS	Id	CDATA	#REQUIRED
			Branch	CDATA	#REQUIRED >

<!-- LOG element; Contains a log of what has been done during this update				-->
<!ELEMENT	LOG	(#PCDATA) >

<!-- PEOPLE; Contains information about the people involved in the update				-->
<!ELEMENT	PEOPLE	(UPDATER, SUBMITTER?, REVIEWER?, APPROVER?) >

<!-- UPDATER element; Contains information about whoever made the update				-->
<!ELEMENT	UPDATER	EMPTY >
<!ATTLIST	UPDATER	Handle	CDATA	#IMPLIED >

<!-- SUBMITTER; Contains information about who submitted the update					-->
<!ELEMENT	SUBMITTER	(#PCDATA) >

<!-- REVIEWER element; Contains information about whoever reviewed the update				-->
<!ELEMENT	REVIEWER	(#PCDATA) >

<!-- APPROVER element; Contains information about whoever approved the update				-->
<!ELEMENT	APPROVER	(#PCDATA) >

<!-- FILES; Contains information about the actual files affected					-->
<!ELEMENT	FILES	(FILE+) >

<!-- FILE; Contains information about what changed with a particular file				-->
<!ELEMENT	FILE	EMPTY >
<!ATTLIST	FILE	Path		CDATA	#REQUIRED
			Action		(Add|Delete|Modify) "Modify"
			Revision	CDATA	#IMPLIED
			Changes		CDATA	#IMPLIED >

<!-- MESSAGE element; Contains information about the email						-->
<!ELEMENT	MESSAGE	(DATE, TIME, REPOSITORY, TO+) >
<!ATTLIST	MESSAGE	Id				CDATA	#REQUIRED
					Subject			CDATA	#REQUIRED
					EncodingLosses	BOOLEAN #REQUIRED >

<!-- REPOSITORY element; Specifies which repository this commit acts against					-->
<!ELEMENT	REPOSITORY	(#PCDATA) >

<!-- TO element; Contains information about who the message was sent to					-->
<!ELEMENT	TO	EMPTY >
<!ATTLIST	TO	Email	CDATA	#REQUIRED >

<!-- PR element; Contains information about the Problem Report						-->
<!ELEMENT	PR	(#PCDATA) >
<!ATTLIST	PR	Id	CDATA	#IMPLIED >

<!-- DATE element;  Allows dates from 1990.01.01 through 2010.12.31					-->
<!ENTITY	% Years		"(1990|1991|1992|1993|1994|1995|1996|1997|1998|1999|2000|2001|2002|2003|2004|2005|2006|2007|2008|2009|2010)" >
<!ENTITY	% Months	"(1|2|3|4|5|6|7|8|9|10|11|12)" >
<!ENTITY	% Days		"(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)" >
<!ELEMENT	DATE	EMPTY >
<!ATTLIST	DATE	Year	%Years;		#REQUIRED
			Month	%Months;	#REQUIRED
			Day	%Days;		#REQUIRED >

<!-- TIME element;  Allows all times, with field for timezone						-->
<!ENTITY	% Hours		"(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23)" >
<!ENTITY	% Minutes	"(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|28|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59)" >
<!ENTITY	% Seconds	"(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|28|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59)" >
<!ELEMENT	TIME	EMPTY >
<!ATTLIST	TIME	Hour		%Hours;		#REQUIRED
			Minute		%Minutes;	#REQUIRED
			Second		%Seconds;	#REQUIRED
			Timezone	CDATA		#REQUIRED >

<!ENTITY	% boolean	"(true|false)">

=== dlangille/freshports-1/docs/commits.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE UPDATES PUBLIC "-//FreshPorts//DTD FreshPorts 2.0//EN" "http://www.freshports.org/docs/fp-updates.dtd">

<UPDATES>
	<UPDATE>
		<DATE Year="2000" Month="12" Day="29" />
		<TIME Hour="17" Minute="51" Second="13" Timezone="PST" />
		<OS Id="FreeBSD" Branch="RELENG_4" />
		<LOG>MFC vfs_bio.c 1.269 and friends.  This MFC's the better launder limiting
solution.  See commitlogs/sys '2000/12/26 11:41:38 PST'</LOG>
		<PEOPLE>
			<UPDATER Handle="dillon" />
		</PEOPLE>
		<FILES>
			<FILE Action="Modify" Revision="1.242.2.5" Changes="+131 -138" Path="src/sys/kern/vfs_bio.c" />
			<FILE Action="Modify" Revision="1.92.2.3" Changes="+11 -3" Path="src/sys/kern/vfs_cluster.c" />
			<FILE Action="Modify" Revision="1.90.2.2" Changes="+3 -1" Path="src/sys/miscfs/devfs/Attic/devfs_vnops.c" />
			<FILE Action="Modify" Revision="1.131.2.2" Changes="+3 -1" Path="src/sys/miscfs/specfs/spec_vnops.c" />
			<FILE Action="Modify" Revision="1.88.2.3" Changes="+3 -1" Path="src/sys/sys/buf.h" />
			<FILE Action="Modify" Revision="1.111.2.4" Changes="+2 -1" Path="src/sys/sys/vnode.h" />
			<FILE Action="Modify" Revision="1.65.2.6" Changes="+4 -2" Path="src/sys/ufs/ufs/ufs_readwrite.c" />
			<FILE Action="Modify" Revision="1.147.2.5" Changes="+3 -1" Path="src/sys/vm/vm_page.c" />
			<FILE Action="Modify" Revision="1.75.2.5" Changes="+2 -1" Path="src/sys/vm/vm_page.h" />
			<FILE Action="Modify" Revision="1.151.2.7" Changes="+114 -113" Path="src/sys/vm/vm_pageout.c" />
			<FILE Action="Modify" Revision="1.116.2.3" Changes="+37 -5" Path="src/sys/vm/vnode_pager.c" />
		</FILES>
		<MESSAGE Id="200012300151.eBU1pDw49826@freefall.freebsd.org" Sender="Matt Dillon &lt;dillon@FreeBSD.org&gt;" Subject="cvs commit: src/sys/kern vfs_bio.c vfs_cluster.c
src/sys/miscfs/devfs devfs_vnops.c src/sys/miscfs/specfs
spec_vnops.c src/sys/sys buf.h vnode.h src/sys/ufs/ufs
ufs_readwrite.c src/sys/vm vm_page.c vm_page.h vm_pageout.c ...">
			<DATE Year="2000" Month="12" Day="29" />
			<TIME Hour="17" Minute="51" Second="13" Timezone="PST" />
			<TO Email="cvs-committers@FreeBSD.org" />
			<TO Email="cvs-all@FreeBSD.org" />
		</MESSAGE>
	</UPDATE>
</UPDATES>

=== dlangille/freshports-1/docs/sample_message.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE UPDATES PUBLIC "-//FreshPorts//DTD FreshPorts 2.0//EN" "http://www.freshports.org/docs/fp-updates.dtd">

<UPDATES>
    <UPDATE>
        <DATE Year="2000" Day="25" Month="12"></DATE>
        <TIME Minute="21" Timezone="PST" Second="18" Hour="1"></TIME>
        <OS Id="FreeBSD" Branch="HEAD"></OS>
        <LOG>Add support for PC-card router configuration. (MFPAO)

o Add the removable_interfaces variable for list of removable network
  interfaces (PC-card ethernet, wireless network and USB ethernet etc).
o ifconfig_&lt;ifn&gt;_alias0, static_routes_&lt;ifn&gt;, removable_route_flush,
  /etc/start_if.&lt;ifn&gt; and /etc/stop_if.&lt;ifn&gt; are support.
o removable_route_flush variable is set to "NO" if you want to use the
  machine as gateway using two or more removable network cards. If
  static routing is needed use static_routes_&lt;ifn&gt; instead of
  static_routes or defaultrouter.
o The optional static_routes_&lt;ifn&gt; variable is likely static_routes.
o /etc/start_if.&lt;ifn&gt; and /etc/stop_if.&lt;ifn&gt; are shell script to be
  specified that are called when a card is inserted or remove</LOG>
        <PEOPLE>
            <UPDATER Handle="toshi"></UPDATER>
        </PEOPLE>
        <MESSAGE Subject="cvs commit: src/etc pccard_ether" Id="200012250921.eBP9LIH17780@freefall.freebsd.org">
            <DATE Year="25" Day="2000" Month="12"></DATE>
            <TIME Minute="21" Timezone="PST" Second="18" Hour="1"></TIME>
            <TO Email="cvs-committers@FreeBSD.ORG"></TO>
            <TO Email="cvs-all@FreeBSD.ORG"></TO>
        </MESSAGE>
    </UPDATE>
</UPDATES>

=== dlangille/freshports-1/docs/scripts/email.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE UPDATES PUBLIC "-//FreshPorts//DTD FreshPorts 2.0//EN" "http://www.freshports.org/docs/fp-updates.dtd">

<UPDATES Version="1.3.2.1">
    <UPDATE>
        <DATE Year="2003" Day="1" Month="6"></DATE>
        <TIME Minute="3" Timezone="PDT" Second="9" Hour="8"></TIME>
        <OS Id="FreeBSD" Branch="HEAD"></OS>
        <LOG>Merge from the English version:

  1.141  -&gt; 1.146 fr/news/news.xml
  1.62   -&gt; 1.70  fr/news/press.xml</LOG>
        <PEOPLE>
            <UPDATER Handle="stephane"></UPDATER>
        </PEOPLE>
        <MESSAGE EncodingLosses="false" Subject="cvs commit: www/fr/news news.xml press.xml" Id="200306011503.h51F39DZ038530@repoman.freebsd.org">
            <DATE Year="2003" Day="1" Month="6"></DATE>
            <TIME Minute="3" Timezone="PDT" Second="9" Hour="8"></TIME>
            <TO Email="doc-committers@FreeBSD.org"></TO>
            <TO Email="cvs-doc@FreeBSD.org,"></TO>
        </MESSAGE>
        <FILES>
            <FILE Changes="+73 -4" Path="www/fr/news/news.xml" Action="Modify" Revision="1.5"></FILE>
            <FILE Changes="+108 -2" Path="www/fr/news/press.xml" Action="Modify" Revision="1.2"></FILE>
        </FILES>
    </UPDATE>
</UPDATES>
